// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/api/tracks/index.ts";
import * as $2 from "./routes/api/tracks/latest.ts";
import * as $3 from "./routes/index.tsx";
import * as $$0 from "./islands/Jukebox.tsx";
import * as $$1 from "./islands/Sidebar.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/api/tracks/index.ts": $1,
    "./routes/api/tracks/latest.ts": $2,
    "./routes/index.tsx": $3,
  },
  islands: {
    "./islands/Jukebox.tsx": $$0,
    "./islands/Sidebar.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
